import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider"
import Script from "next/script";
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'StepbyStep Blog',
    description: 'Generated by create next app',
}
export const viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimuxScale: 1,
    userScalable: 0,
  }
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="light" style={{colorScheme: "light"}}>
            <Script defer src="https://eu.umami.is/script.js"
                    data-website-id="c1c14533-41c6-400b-ba8d-7c7356e85a1d"/>

        <body className={`${inter.className} bg-[#f6f6fa] dark:bg-[#18191A]`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >

            {children}
            <Toaster/>
        </ThemeProvider>
        </body>
        </html>
    )
}

  